version: '3.8'

services:
  tree-structure-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - neo4j
    environment:
      JDBC_DATABASE_URL: jdbc:neo4j:bolt://neo4j:7687/?user=neo4j,password=password,scheme=basic
    networks:
      - backend

  neo4j:
    image: neo4j:3.5.28-community
    ports:
      - 7687:7687 #Bolt
      - 7474:7474 #HTTP
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data/
    networks:
      - backend

volumes:
  neo4j_data:

networks:
  backend: